---
title: "synoptic_workspace"
author: "Zack Grzywacz"
date: "March 2, 2021"
output: html_document
---

```{r}
library(dplyr)
library(DataCombine)
```


```{r}
daily <- read.delim("./data/SOM_daily_z500_anomaly_3_3.txt", sep = " ")
```


Here:
Basically creating the same dataset Udy did, where each season has detailed counts.

Also: treat it as a time series w/monthly percentages

```{r}
daily$year <- substr(daily$date, 1, 4)
daily$month <- substr(daily$date, 5,6)
daily$year <- as.numeric(daily$year)
daily$month <- as.numeric(daily$month)
```


```{r}
daily$season <- NA
for (x in 1:nrow(daily))
{
  if (daily$month[x] == 12 | daily$month[x] == 1 | daily$month[x] == 2){
    daily$season[x] <- 'DJF'
  }
  else if (daily$month[x] == 3 | daily$month[x] == 4 | daily$month[x] == 5){
    daily$season[x] <- 'MAM'
  }
  else if (daily$month[x] == 6 | daily$month[x] == 7 | daily$month[x] == 8){
    daily$season[x] <- 'JJA'
  }
  else if (daily$month[x] == 9 | daily$month[x] == 10 | daily$month[x] == 11){
    daily$season[x] <- 'SON'
  }
}
```


*Note: June - May might be the "year" to look at (number assigned being June - Dec year)
```{r}
daily$seas_yr <- 0
for (x in 1:nrow(daily))
{
  if (daily[x,4] == 1 | daily[x,4] == 2 | daily[x,4] == 3 | daily[x,4] == 4 | daily[x,4] == 5)
  {
    daily$seas_yr[x] <- (daily$year[x]-1)
  }
  else
  {
    daily$seas_yr[x] <- daily$year[x]
  }
}
```

```{r}
DJF_daily <- subset(daily, season == 'DJF')
MAM_daily <- subset(daily, season == 'MAM')
JJA_daily <- subset(daily, season == 'JJA')
SON_daily <- subset(daily, season == 'SON')
```


```{r}
daily_summary <- daily %>% group_by(seas_yr, season, node) %>% summarise(n=n())
daily_summary_yrs <- daily %>% group_by(seas_yr, node) %>% summarise(n=n())
```

```{r}
split_years <- split(daily_summary_yrs, daily_summary_yrs$seas_yr)
```

```{r}
yr_range <- c(1979:2017)
nodes <- 1:9
summarized <- data.frame("SOM1"=double(),"SOM2"=double(),"SOM3"=double(),"SOM4"=double(),"SOM5"=double(),"SOM6"=double(),"SOM7"=double(),"SOM8"=double(),"SOM9"=double())
for (year in 1979:2017)
{
  yr <- toString(year)
  datapoint <- data.frame(t(split_years[[yr]] %>% group_by(node) %>% summarise(percent = n/sum(split_years[[yr]]$n)*100)))
  rownames(datapoint) <- NULL
  names(datapoint) <- names(summarized)
  summarized <- rbind(summarized,datapoint[2,])
}
row.names(summarized) <- yr_range
annual_summary <- summarized
```



```{r}
summarize_SOM_data <- function(daily){
daily_summary <- daily %>% group_by(seas_yr, season, node) %>% summarise(n=n())
daily_summary_yrs <- daily %>% group_by(seas_yr, node) %>% summarise(n=n())
split_years <- split(daily_summary_yrs, daily_summary_yrs$seas_yr)
yr_range <- c(1979:2017)
nodes <- 1:9
summarized <- data.frame("SOM1"=double(),"SOM2"=double(),"SOM3"=double(),"SOM4"=double(),"SOM5"=double(),"SOM6"=double(),"SOM7"=double(),"SOM8"=double(),"SOM9"=double())
for (year in 1979:2017)
{
  yr <- toString(year)
  for (num in 1:9){
    if (num %in% split_years[[yr]]$node == 'FALSE'){
      newrow <- c(year,num,0)  
      names(newrow) <- c("seas_yr","node","n")
      split_years[[yr]] <- rbind(split_years[[yr]], newrow)
    }
  }
  datapoint <- data.frame(t(split_years[[yr]] %>% group_by(node) %>% summarise(percent = n/sum(split_years[[yr]]$n)*100)))
  rownames(datapoint) <- NULL
  names(datapoint) <- names(summarized)
  summarized <- rbind(summarized,datapoint[2,])
}
row.names(summarized) <- yr_range
return(summarized)
}
```

```{r}
JJA_summary <- summarize_SOM_data(JJA_daily)
SON_summary <- summarize_SOM_data(SON_daily)
DJF_summary <- summarize_SOM_data(DJF_daily)
MAM_summary <- summarize_SOM_data(MAM_daily)
```







```{r}
cg_DJF <- read.csv("data/CG_DJF_means.csv")
summer_mean <- mean(cg_DJF$DJF_Mean)
cg_DJF$anom <- (cg_DJF$DJF_Mean - summer_mean)
rownames(cg_DJF) <- cg_DJF[,1]
cg_DJF[,1] <- NULL
cg_DJF
DJF_full <- merge(DJF_summary,cg_DJF,by=0)
rownames(DJF_full) <- DJF_full[,1]
DJF_full[,1] <- NULL
```

```{r}
DJF_corrs <- cor(DJF_full, method = c("pearson", "kendall", "spearman"))
```


```{r}
cg_SON <- read.csv("data/CG_SON_means.csv")
season_mean <- mean(cg_SON$SON_Mean)
cg_SON$anom <- (cg_SON$SON_Mean - season_mean)
rownames(cg_SON) <- cg_SON[,1]
cg_SON[,1] <- NULL
cg_SON
SON_full <- merge(SON_summary,cg_SON,by=0)
rownames(SON_full) <- SON_full[,1]
SON_full[,1] <- NULL
```

```{r}
SON_corrs <- cor(SON_full, method = c("pearson", "kendall", "spearman"))
```

```{r}
cg_MAM <- read.csv("data/CG_MAM_means.csv")
season_mean <- mean(cg_MAM$MAM_Mean)
cg_MAM$anom <- (cg_MAM$MAM_Mean - season_mean)
rownames(cg_MAM) <- cg_MAM[,1]
cg_MAM[,1] <- NULL
cg_MAM
MAM_full <- merge(MAM_summary,cg_MAM,by=0)
rownames(MAM_full) <- MAM_full[,1]
MAM_full[,1] <- NULL
```

```{r}
MAM_corrs <- cor(MAM_full, method = c("pearson", "kendall", "spearman"))
```

```{r}
cg_JJA <- read.csv("data/CG_JJA_means.csv")
season_mean <- mean(cg_JJA$JJA_Mean)
cg_JJA$anom <- (cg_JJA$JJA_Mean - season_mean)
rownames(cg_JJA) <- cg_JJA[,1]
cg_JJA[,1] <- NULL
cg_JJA
JJA_full <- merge(JJA_summary,cg_JJA,by=0)
rownames(JJA_full) <- JJA_full[,1]
JJA_full[,1] <- NULL
```

```{r}
JJA_corrs <- cor(JJA_full, method = c("pearson", "kendall", "spearman"))
```


```{r}
SON_corrs
```

```{r}
plot(DJF_full$DJF_Mean, DJF_full$SOM3)
```





**Working with monthly**


```{r}
monthlies <- daily %>% group_by(year, month, node) %>% summarise(n=n())
```




```{r}
split_months <- split(monthlies, monthlies$month)
monthlist <- vector(mode = "list", length = 0)
for (x in 1:12){
  mo <- toString(x)
  templist <- split(split_months[[mo]], split_months[[mo]]$year)
  monthlist[[mo]] <- templist 
}
```



```{r}
yr_range <- c(1979:2017)
nodes <- 1:9
MonthSummary <- data.frame("SOM1"=double(),"SOM2"=double(),"SOM3"=double(),"SOM4"=double(),"SOM5"=double(),"SOM6"=double(),"SOM7"=double(),"SOM8"=double(),"SOM9"=double())
for (year in 1979:2017)
{
  yr <- toString(year)
  for (month in 1:12){
    mo <- toString(month)
    for (num in 1:9){
      if (num %in% monthlist[[mo]][[yr]]$node == 'FALSE'){
        newrow <- c(year,month,num,0)  
        names(newrow) <- c("year","month","node","n")
        monthlist[[mo]][[yr]] <- rbind(monthlist[[mo]][[yr]], newrow)
        }
      }
    datapoint <- data.frame(t(monthlist[[mo]][[yr]] %>% group_by(node) %>% summarise(percent = n/sum(monthlist[[mo]][[yr]]$n)*100)))
    rownames(datapoint) <- NULL
    names(datapoint) <- names(MonthSummary)
    MonthSummary <- rbind(MonthSummary,datapoint[2,])
  }
}
m <- rep(01:12, 39)
y <- rep(1979:2017, each=12)
row.names(MonthSummary) <- paste(m,y, sep = "-", collapse = NULL)
```


```{r}
full_CG <- read.csv("./data/CG_GNIP.csv")
rownames(full_CG) <- full_CG[,1]
full_CG[,1] <- NULL
```



```{r}
monthly_CG <- merge(MonthSummary,full_CG,by=0)
rownames(monthly_CG) <- monthly_CG[,1]
monthly_CG[,1] <- NULL
```

```{r}
cor(na.omit(monthly_CG))
```

Compositing:

```{r}
top10o18 <- top_n(monthly_CG, 10)
bottom10o18 <- top_n(monthly_CG, -10)
colMeans(top10o18)
colMeans(bottom10o18)
```


Anomalies:

```{r}
monthly_mean <- mean(na.omit(monthly_CG$O18))
monthly_CG$anom <- (monthly_CG$O18 - monthly_mean)
```



